language: python

python:
  - "3.7-dev"  # 3.7 development branch

notifications:
  email: false

before_install:
  - docker build --no-cache=true -t "benblamey/image_analysis_container2:latest" .

install:
  - pip install .

script:
  - pytest

